import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./style.css";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className={` ${interFont.variable} antialiased`}>
      {children}
    </section>
  );
}
